### ISSUE TITLE
Problem with vagrant quickstart - no hypercube running

### ISSUE THREAD

**Issue by zefciu** [projectcalico/calico-containers#1045]
I try to run the configuration from https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/VagrantCoreOS.md

After I run vagrant up and ssh to the master I cannot issue any kubectl commands. What I get is

```Unable to connect to the server: dial tcp: lookup localhost on 10.0.2.3:53: too many redirects```

It seems that kubectl is not configured properly on this machine.

**Comment by caseydavenport** [comment]
The face that hyperkube isn't running is expected - this guide uses cloud-config [here](https://github.com/projectcalico/calico-containers/tree/master/docs/cni/kubernetes/vagrant-coreos/cloud-config) to run the kubernetes components under `systemd`.

I just tried running this myself and didn't encounter the same issue.  It looks like it's attempting to do a DNS lookup for `localhost` on `10.0.2.3:53` but failing.  Could you try adding a line to `/etc/hosts` which resolves localhost to 127.0.0.1?

**Comment by zefciu** [comment]
I saw later, that hypercube wasn't containerised. I fixed the problem with bad IP by configuring kubectl to use 127.0.0.1. Next week I will create a patch, that will fix this and one other problem, so that the Vagrantfile works out of the box.

**Comment by jdoucy** [comment]
I think I'm facing the same issue, but not sure, just finish to vagrant up, connect to k8s-master, and try to launch some Kubectl commands. Not working, first get:
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`
So trying to do what @zefciu did:
`kubectl get services --server='http://127.0.0.1:8080'`
and get:
`The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?
`
Is it the same issue?
Is hypercube running after vagrant up?

**Comment by zefciu** [comment]
Did you try my patch?
https://github.com/projectcalico/calico-containers/pull/1060

**Comment by jdoucy** [comment]
Yes I just apply your patch, `vagrant destroy`, `vagrant up`, and still the same issue. But now I have this when logging into `k8s-master`:

```
CoreOS stable (1068.8.0)
Last login: Wed Aug  3 14:33:05 2016 from 10.0.2.2
Update Strategy: No Reboots
Failed Units: 1
  kube-proxy.service
```

I suppose that failed units is not a good thing.
